version: '3.8'

services:

  provider:
    container_name: provider
    build:
      context: ../launcher
    environment:
      APPLICATIONINSIGHTS_CONNECTION_STRING: ${APPLICATIONINSIGHTS_CONNECTION_STRING}
      APPLICATIONINSIGHTS_ROLE_NAME: provider
      APPLICATIONINSIGHTS_INSTRUMENTATION_LOGGING_LEVEL: DEBUG
      IDS_WEBHOOK_ADDRESS: http://provider:8282
      EDC_VAULT_NAME: ${PROVIDER_KEY_VAULT}
      EDC_VAULT_TENANTID: ${EDC_VAULT_TENANTID}
      EDC_VAULT_CLIENTID: ${EDC_VAULT_CLIENTID}
      EDC_VAULT_CLIENTSECRET: ${EDC_VAULT_CLIENTSECRET}
    ports:
      - 9191:9191

  consumer:
    container_name: consumer
    build:
      context: ../launcher
    environment:
      APPLICATIONINSIGHTS_CONNECTION_STRING: ${APPLICATIONINSIGHTS_CONNECTION_STRING}
      APPLICATIONINSIGHTS_ROLE_NAME: consumer
      APPLICATIONINSIGHTS_INSTRUMENTATION_LOGGING_LEVEL: DEBUG
      IDS_WEBHOOK_ADDRESS: http://consumer:8282
      EDC_VAULT_NAME: ${CONSUMER_KEY_VAULT}
      EDC_VAULT_TENANTID: ${EDC_VAULT_TENANTID}
      EDC_VAULT_CLIENTID: ${EDC_VAULT_CLIENTID}
      EDC_VAULT_CLIENTSECRET: ${EDC_VAULT_CLIENTSECRET}
    ports:
      - 9192:9191
