name: CD

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'

env:
  # Update this value with a unique name to guarantee uniqueness of resource names and avoid conflicts between fork repositories when running CD workflow.
  # CD workflow creates resources with this prefix and destroy them.
  CD_RESOURCES_PREFIX: mvd

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yaml
  destroy:
    uses: ./.github/worlflows/destroy.yaml
    with:
      resources_prefix: ${CD_RESOURCES_PREFIX}
