name: CD

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'


# Grant permissions to obtain federated identity credentials
# see https://docs.github.com/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-azure
permissions:
  id-token: write
  contents: read

jobs:

  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: MVD

      - uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Checkout EDC
        uses: actions/checkout@v2
        with:
          repository: eclipse-dataspaceconnector/DataSpaceConnector
          path: DataSpaceConnector

      - name: Cache EDC modules
        uses: actions/cache@v3
        id: cache
        with:
          path: ~/.m2
          # .git/FETCH_HEAD contains latest commit ID
          key: ${{ runner.os }}-m2-${{ hashFiles('DataSpaceConnector/.git/FETCH_HEAD') }}

      - run: find ~/.m2

      - name: Build EDC modules
        run: ./gradlew publishToMavenLocal
        if: steps.cache.outputs.cache-hit != 'true' # only on cache miss
        working-directory: DataSpaceConnector

      - run: ./gradlew launcher:shadowJar
        working-directory: MVD

      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - run: az acr login -n $ACR_NAME
        env:
          ACR_NAME: ${{ secrets.ACR_NAME }}

      - run: az acr build --registry $ACR_NAME --image mvd-edc/connector:latest .
        working-directory: MVD
        env:
          ACR_NAME: ${{ secrets.ACR_NAME }}

  Deploy:
    matrix:
      - ZF
      - Bosch
    needs: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: "Run terraform"
        run: terraform apply
        env:
          ACR_NAME: ${{ secrets.ACR_NAME }}
          TF_VAR_participant_name: ${{matrix.name}}
          TF_VAR_prefix: ${{github.job.id}}

      - uses: upload/artifact
        path: tfstate

  Destroy:
    matrix:
      - ZF
      - Bosch
    needs: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - uses: download/artifact
        path: tfstate

      - name: "Run terraform"
        run: terraform destroy
        if: branch 
        env:
          ACR_NAME: ${{ secrets.ACR_NAME }}
          TF_VAR_participant_name: ${{matrix.name}}
          TF_VAR_prefix: ${{github.job.id}}