name: CD

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'

# Grant permissions to obtain federated identity credentials
# see https://docs.github.com/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-azure
permissions:
  id-token: write
  contents: read

env:
  # Update this value with a unique name to guarantee uniqueness of resource names and avoid conflicts between fork repositories when running CD workflow.
  # CD workflow creates resources with this prefix and destroy them.
  CD_RESOURCES_PREFIX: agc

jobs:
  # Used a step to set up resources_prefix as an output, because env context is not available from a caller workflow
  # See this discussion for more context: https://github.community/t/reusable-workflow-env-context-not-available-in-jobs-job-id-with/206111/13
  set-resources-prefix:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
    outputs:
      resources_prefix: ${{ env.CD_RESOURCES_PREFIX }}${{ github.run_number }}

  deploy:
    uses: ./.github/workflows/deploy.yaml
    secrets: inherit
    with:
      resources_prefix: ${{ needs.set-resources-prefix.outputs.resources_prefix }}

  destroy:
    uses: ./.github/workflows/destroy.yaml
    needs: deploy
    secrets: inherit
    with:
      resources_prefix: ${{ needs.set-resources-prefix.outputs.resources_prefix }}

