name: CD

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'

# Grant permissions to obtain federated identity credentials
# see https://docs.github.com/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-azure
permissions:
  id-token: write
  contents: read

env:
  # Update this value with a unique name to guarantee uniqueness of resource names and avoid conflicts between fork repositories when running CD workflow.
  # CD workflow creates resources with this prefix and destroy them.
  CD_RESOURCES_PREFIX: agc

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yaml
    secrets: inherit
    with:
      resources_prefix: agc${{ github.run_number }}

  destroy:
    uses: ./.github/workflows/destroy.yaml
    needs: deploy
    secrets: inherit
    with:
      resources_prefix: agc${{ github.run_number }}

