name: CD

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'


# Grant permissions to obtain federated identity credentials
# see https://docs.github.com/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-azure
permissions:
  id-token: write
  contents: read

jobs:

  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        repo: https://github.com/eclipse-dataspaceconnector/DataSpaceConnector

      # Write JARs to ~/.m2
      - run: gradlew publishToMavenLocal
        workingDirectory: DataSpaceConnector

      - run: gradle mvd:launcher:connector:shadowJar

      - run: az acr build --registry $ACR_NAME --image mvd-edc/connector:latest  .
        env:
          ACR_NAME: ${{ secrets.ACR_NAME }}

jobs:

  Deploy:
    matrix:
      - ZF
      - Bosch
    needs: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: "Run terraform"
        run: terraform apply
        env:
          ACR_NAME: ${{ secrets.ACR_NAME }}
          TF_VAR_participant_name: ${{matrix.name}}
          TF_VAR_prefix: ${{github.job.id}}

      - uses: upload/artifact
        path: tfstate

  Destroy:
    matrix:
      - ZF
      - Bosch
    needs: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - uses: download/artifact
        path: tfstate

      - name: "Run terraform"
        run: terraform destroy
        if: branch 
        env:
          ACR_NAME: ${{ secrets.ACR_NAME }}
          TF_VAR_participant_name: ${{matrix.name}}
          TF_VAR_prefix: ${{github.job.id}}