name: CD

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'

# Grant permissions to obtain federated identity credentials
# see https://docs.github.com/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-azure
permissions:
  id-token: write
  contents: read

# Update this value with a unique name to guarantee uniqueness of resource names and avoid conflicts between fork repositories when running CD workflow.
# CD workflow creates resources with this prefix and destroy them.
env:
  CD_RESOURCES_PREFIX: agc

jobs:
  # The purpose of this job is only to set up resources_prefix as an output, because env context is not available from a caller workflow
  # See this discussion for more context: https://github.community/t/reusable-workflow-env-context-not-available-in-jobs-job-id-with/206111/13
  set_resources_prefix:
    runs-on: ubuntu-latest
    # Added a step doing nothing, because a job needs to have at least one step.
    steps:
      - name: 'Set resources prefix.'
        run: exit 0
    outputs:
      resources_prefix: ${{ env.CD_RESOURCES_PREFIX }}${{ github.run_number }}

  deploy:
    uses: ./.github/workflows/deploy.yaml
    secrets: inherit
    needs: set_resources_prefix
    with:
      resources_prefix: ${{ needs.set_resources_prefix.outputs.resources_prefix }}

  destroy:
    uses: ./.github/workflows/destroy.yaml
    needs: [set_resources_prefix, deploy]
    secrets: inherit
    with:
      resources_prefix: ${{ needs.set_resources_prefix.outputs.resources_prefix }}
