name: Initialize CD

on: workflow_dispatch

# Grant permissions to obtain federated identity credentials
# see https://docs.github.com/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-azure
permissions:
  id-token: write
  contents: read

jobs:

  Deploy:
    runs-on: ubuntu-latest

    env:
      ACR_RESOURCE_GROUP: ${{ secrets.ACR_RESOURCE_GROUP }}
      ACR_RESOURCE_GROUP_LOCATION: ${{ secrets.ACR_RESOURCE_GROUP_LOCATION }}
      ACR_NAME: ${{ secrets.ACR_NAME }}

    steps:
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: "Create resource group"
        run: az group create --name "$ACR_RESOURCE_GROUP" --location "$ACR_RESOURCE_GROUP_LOCATION" -o table

      - name: "Create resource group"
        run: az acr create --resource-group "$ACR_RESOURCE_GROUP" --name "$ACR_NAME" --sku Basic -o table